#!/bin/bash
### BEGIN INIT INFO
# Provides:          nimiq
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Halts USB power...
### END INIT INFO
/home/ubuntu/./skypool-node-client
